[package]
name = "ledger"
version = "0.1.0"
edition = "2021"
default-run = "ledger"

[dependencies]
sha2 = "0.10.6"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
hex = "0.4.3"
rand = "0.9.0"
log = "0.4.27"
flexi_logger = "0.30.1"
bincode = "2.0.1"
thiserror = "2.0.12"